"""initial schema

Revision ID: 1b8f9ae19d8e
Revises: 
Create Date: 2026-09-19 10:09:13.359130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8f9ae19d8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('income', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('loan_amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('credit_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('months_employed', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('num_credit_lines', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('interest_rate', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('loan_term', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('dti_ratio', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('has_mortgage', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('has_dependents', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('has_co_signer', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('education_high_school', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('education_masters', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('education_phd', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('employment_type_part_time', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('employment_type_self_employed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('employment_type_unemployed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('marital_status_married', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('marital_status_single', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('loan_purpose_business', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('loan_purpose_education', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('loan_purpose_home', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('loan_purpose_other', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('loan_purpose_other')
        batch_op.drop_column('loan_purpose_home')
        batch_op.drop_column('loan_purpose_education')
        batch_op.drop_column('loan_purpose_business')
        batch_op.drop_column('marital_status_single')
        batch_op.drop_column('marital_status_married')
        batch_op.drop_column('employment_type_unemployed')
        batch_op.drop_column('employment_type_self_employed')
        batch_op.drop_column('employment_type_part_time')
        batch_op.drop_column('education_phd')
        batch_op.drop_column('education_masters')
        batch_op.drop_column('education_high_school')
        batch_op.drop_column('has_co_signer')
        batch_op.drop_column('has_dependents')
        batch_op.drop_column('has_mortgage')
        batch_op.drop_column('dti_ratio')
        batch_op.drop_column('loan_term')
        batch_op.drop_column('interest_rate')
        batch_op.drop_column('num_credit_lines')
        batch_op.drop_column('months_employed')
        batch_op.drop_column('credit_score')
        batch_op.drop_column('loan_amount')
        batch_op.drop_column('income')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
