"""add shap_values to applications

Revision ID: 6dfcfb8d881f
Revises: 1b8f9ae19d8e
Create Date: 2026-09-20 09:41:57.430147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfcfb8d881f'
down_revision = '1b8f9ae19d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shap_values', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('shap_values')

    # ### end Alembic commands ###
