"""add is_active to banks

Revision ID: c80d146a8533
Revises: 6dfcfb8d881f
Create Date: 2026-09-25 08:13:07.863719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c80d146a8533'
down_revision = '6dfcfb8d881f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
